# Generated by Django 3.1.7 on 2021-09-10 07:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zone", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceFormMasterProctorShip",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                (
                    "attendance_form",
                    models.FileField(
                        blank=True,
                        db_column="AttendanceForm",
                        default=None,
                        null=True,
                        upload_to="uploads/",
                    ),
                ),
            ],
            options={
                "db_table": "AttendanceFormMasterProctorShip",
            },
        ),
        migrations.CreateModel(
            name="InvoiceMasterProctorShip",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        db_column="InvoiceNumber",
                        default=None,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "fee_covered",
                    models.CharField(
                        db_column="FEECoveredbyMedicalAffair",
                        default="",
                        max_length=255,
                    ),
                ),
                (
                    "other_cost",
                    models.CharField(
                        db_column="OtherCostsCoveredByMedicalAffair",
                        default="",
                        max_length=255,
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(db_column="DateOfInvoice", default=None),
                ),
                ("note", models.TextField(db_column="Note", default="")),
                (
                    "invoice_sent",
                    models.BooleanField(
                        db_column="InvoicesSentToTheAdministration", default=False
                    ),
                ),
            ],
            options={
                "db_table": "InvoiceMasterProctorShip",
            },
        ),
        migrations.CreateModel(
            name="MasterProctorship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                (
                    "reason",
                    models.CharField(db_column="Reason", default="", max_length=255),
                ),
                ("note", models.TextField(db_column="Note")),
                (
                    "hotel",
                    models.CharField(db_column="HotelName", default="", max_length=255),
                ),
                ("number_of_cases", models.IntegerField(db_column="NumberofCases")),
                (
                    "transplant_time",
                    models.CharField(
                        db_column="TransplantTime", default="", max_length=255
                    ),
                ),
            ],
            options={
                "db_table": "MasterProctorship",
            },
        ),
        migrations.CreateModel(
            name="MasterProctorShipConstantData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                (
                    "code",
                    models.SlugField(db_column="Code", default="", max_length=255),
                ),
                (
                    "name",
                    models.CharField(db_column="Name", default="", max_length=255),
                ),
            ],
            options={
                "db_table": "MasterProctorShipConstantData",
            },
        ),
        migrations.CreateModel(
            name="MasterProctorshipFeedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                (
                    "num_of_patients",
                    models.IntegerField(
                        db_column="HowManyOatientSelected", default=None
                    ),
                ),
                (
                    "rate_of_proceduresc",
                    models.CharField(
                        blank=True,
                        db_column="RateOfProceduralStep",
                        default="",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "new_proctor_need_further_training",
                    models.BooleanField(
                        db_column="NewProctorNeedFurtherTraining", default=False
                    ),
                ),
                (
                    "suggestion",
                    models.CharField(
                        blank=True,
                        db_column="Suggestions",
                        default="",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "report",
                    models.FileField(
                        blank=True,
                        db_column="FeedbackReport",
                        default=None,
                        null=True,
                        upload_to="uploads/",
                    ),
                ),
            ],
            options={
                "db_table": "MasterProctorshipFeedback",
            },
        ),
        migrations.CreateModel(
            name="MasterProctorshipProctorReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                (
                    "num_of_patients",
                    models.IntegerField(
                        db_column="NumberOfPatients", default=None, null=True
                    ),
                ),
                (
                    "num_of_perceval",
                    models.IntegerField(
                        db_column="NumberOfPercvelImplant", default=None, null=True
                    ),
                ),
                (
                    "have_difficulties",
                    models.BooleanField(
                        db_column="HaveyoufeelanyDifficulty", default=False
                    ),
                ),
                (
                    "need_for_further_training",
                    models.BooleanField(
                        db_column="DidYouFeelNeedForEurtherTraining", default=False
                    ),
                ),
                (
                    "corcym_suggestion",
                    models.TextField(
                        blank=True, db_column="CorcymSuggestions", default="", null=True
                    ),
                ),
                (
                    "proctor_report",
                    models.FileField(
                        blank=True,
                        db_column="ProctorReport",
                        default=None,
                        null=True,
                        upload_to="uploads/",
                    ),
                ),
            ],
            options={
                "db_table": "MasterProctorshipProctorReport",
            },
        ),
        migrations.CreateModel(
            name="MasterProctorshipProctors",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BooleanField(
                        db_column="MasterProctorshipProposalStatus", default=True
                    ),
                ),
                (
                    "note_related_to_proctor",
                    models.TextField(db_column="NoteRelatedToProctor", default=""),
                ),
                (
                    "proctor_order",
                    models.IntegerField(db_column="ProctorOrder", default=None),
                ),
            ],
            options={
                "db_table": "MasterProctorshipProctors",
            },
        ),
        migrations.CreateModel(
            name="MasterProctorshipProposal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                ("note", models.TextField(db_column="Note", default="")),
                ("start_date", models.DateField(db_column="StartDate", default=None)),
                ("end_date", models.DateField(db_column="EndDate", default=False)),
            ],
            options={
                "db_table": "MasterProctorshipProposal",
            },
        ),
        migrations.CreateModel(
            name="MasterProctorshipStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                ("date", models.DateField(auto_now_add=True, db_column="Date")),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_column="TimeStamp", default=django.utils.timezone.now
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        db_column="Reason",
                        default="",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(db_column="IsActive", default=True)),
            ],
            options={
                "db_table": "MasterProctorshipStatus",
            },
        ),
        migrations.CreateModel(
            name="MasterProctorshipTraineeProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "name",
                    models.CharField(db_column="Name", default="", max_length=255),
                ),
                (
                    "surname",
                    models.CharField(db_column="SurName", default="", max_length=255),
                ),
                (
                    "corcym_accompanying_rep",
                    models.CharField(
                        blank=True,
                        db_column="CorcymAccompanyingRep",
                        default="",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("mvr_case_per_year", models.IntegerField(db_column="MVRCasePerYear")),
                (
                    "mvr_case_per_year_by_trainee",
                    models.IntegerField(db_column="MVRCasePerYearByTrainee"),
                ),
                ("note", models.TextField(db_column="Note")),
                ("status", models.BooleanField(db_column="Status", default=False)),
                ("revoke", models.BooleanField(db_column="Revoke", default=False)),
                (
                    "interest_invasive",
                    models.BooleanField(db_column="InterestInvasive", default=False),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        db_column="CountriesTraineeProfileID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traineeprofile_master_proctorship_country",
                        to="zone.countries",
                    ),
                ),
            ],
            options={
                "db_table": "MasterProctorshipTraineeProfile",
            },
        ),
    ]
