# Generated by Django 3.1.7 on 2021-09-10 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proctorship', '0001_initial'),
        ('masterproctorship', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproctorshiptraineeprofile',
            name='current_preferential',
            field=models.ForeignKey(blank=True, db_column='CurrentPreferential', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_proctorship_current_preferential_constantdata', to='proctorship.constantdata'),
        ),
        migrations.AddField(
            model_name='masterproctorshiptraineeprofile',
            name='hospital',
            field=models.ForeignKey(blank=True, db_column='MasterProctorshipTraineeHospitalID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masterproctorship_trainee_hospital', to='api.hospital'),
        ),
        migrations.AddField(
            model_name='masterproctorshiptraineeprofile',
            name='master_proctorship',
            field=models.ForeignKey(blank=True, db_column='MasterProctorshipTraineeProfileId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainee_master_proctorship', to='masterproctorship.masterproctorship'),
        ),
        migrations.AddField(
            model_name='masterproctorshiptraineeprofile',
            name='title',
            field=models.ForeignKey(blank=True, db_column='Title', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_proctorship_title_constantdata', to='proctorship.constantdata'),
        ),
        migrations.AddField(
            model_name='masterproctorshipstatus',
            name='master_proctorship_activity',
            field=models.ForeignKey(blank=True, db_column='MasterProctorshipStatusId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_proctorship_status', to='masterproctorship.masterproctorship'),
        ),
    ]
