# Generated by Django 3.1.7 on 2021-09-10 07:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceFormPerceptorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='DeletedBy', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now=True, db_column='DeletedOn')),
                ('status', models.BigIntegerField(db_column='Status', default=0, help_text='Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose')),
                ('attendance_form', models.FileField(blank=True, db_column='AttendanceForm', default=None, null=True, upload_to='uploads/')),
            ],
            options={
                'db_table': 'AttendanceFormPerceptorship',
            },
        ),
        migrations.CreateModel(
            name='InvoicePerceptorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='DeletedBy', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now=True, db_column='DeletedOn')),
                ('status', models.BigIntegerField(db_column='Status', default=0, help_text='Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose')),
                ('invoice_number', models.CharField(blank=True, db_column='InvoiceNumber', default=None, max_length=255, null=True)),
                ('fee_covered', models.CharField(db_column='FEECoveredbyMedicalAffair', default='', max_length=255)),
                ('other_cost', models.CharField(db_column='OtherCostsCoveredByMedicalAffair', default='', max_length=255)),
                ('invoice_date', models.DateField(db_column='DateOfInvoice', default=None)),
                ('note', models.TextField(db_column='Note', default='')),
                ('invoice_sent', models.BooleanField(db_column='InvoicesSentToTheAdministration', default=False)),
            ],
            options={
                'db_table': 'InvoicePerceptorship',
            },
        ),
        migrations.CreateModel(
            name='Preceptorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='DeletedBy', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now=True, db_column='DeletedOn')),
                ('status', models.BigIntegerField(db_column='Status', default=0, help_text='Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose')),
                ('is_global', models.BooleanField(db_column='IsGlobal', default=False)),
                ('note', models.TextField(db_column='Note')),
            ],
            options={
                'db_table': 'Preceptorship',
            },
        ),
        migrations.CreateModel(
            name='PreceptorshipProctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='DeletedBy', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now=True, db_column='DeletedOn')),
                ('status', models.BooleanField(db_column='PreceptorshipProctorStatus', default=True)),
            ],
            options={
                'db_table': 'PreceptorshipProctors',
            },
        ),
        migrations.CreateModel(
            name='PreceptorshipProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='DeletedBy', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now=True, db_column='DeletedOn')),
                ('note', models.TextField(db_column='Note', default='')),
                ('start_date', models.DateField(db_column='StartDate', default=None)),
                ('end_date', models.DateField(db_column='EndDate', default=False)),
            ],
            options={
                'db_table': 'PreceptorshipProposal',
            },
        ),
        migrations.CreateModel(
            name='PreceptorshipStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='DeletedBy', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now=True, db_column='DeletedOn')),
                ('date', models.DateField(auto_now_add=True, db_column='Date')),
                ('timestamp', models.DateTimeField(db_column='TimeStamp', default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, db_column='Reason', default='', max_length=255, null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
            ],
            options={
                'db_table': 'PreceptorshipStatus',
            },
        ),
        migrations.CreateModel(
            name='PreceptorshipTraineeUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='DeletedBy', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now=True, db_column='DeletedOn')),
                ('status', models.BigIntegerField(db_column='Status', default=0, help_text='Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose')),
                ('number_of_patients', models.IntegerField(db_column='NumberOfPatients', default=None)),
                ('number_of_perceval', models.IntegerField(db_column='NumberOfPerceval', default=None)),
                ('percevel_driver', models.CharField(blank=True, db_column='PercevelDriverId', max_length=255, null=True)),
                ('are_intrested_learning_more', models.BooleanField(db_column='IntrestedInLearningMore', default=False)),
                ('corcym_suggestion', models.TextField(blank=True, db_column='CorcymSuggestions', default='', null=True)),
                ('proctor_report', models.FileField(blank=True, db_column='PreceptorReport', default=None, null=True, upload_to='uploads/')),
                ('is_memo_family', models.BooleanField(db_column='IsMemoFmaily', default=False)),
                ('is_perceval', models.BooleanField(db_column='IsPerceval', default=False)),
                ('is_solo_smart', models.BooleanField(db_column='IsSoloSmart', default=False)),
            ],
            options={
                'db_table': 'PreceptorshipTraineeUploads',
            },
        ),
        migrations.CreateModel(
            name='TraineePreceptorshipProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='DeletedBy', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now=True, db_column='DeletedOn')),
                ('name', models.CharField(db_column='Name', default='', max_length=255)),
                ('surname', models.CharField(db_column='SurName', default='', max_length=255)),
                ('corcym_accompanying_rep', models.CharField(blank=True, db_column='CorcymAccompanyingRep', default='', max_length=255, null=True)),
                ('mvr_case_per_year', models.IntegerField(db_column='MVRCasePerYear')),
                ('mvr_case_per_year_by_trainee', models.IntegerField(db_column='MVRCasePerYearByTrainee')),
                ('note', models.TextField(db_column='Note')),
                ('status', models.BooleanField(db_column='Status', default=False)),
                ('revoke', models.BooleanField(db_column='Revoke', default=False)),
                ('interest_invasive', models.BooleanField(db_column='InterestInvasive', default=False)),
                ('country', models.ForeignKey(blank=True, db_column='CountriesTraineeProfileID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traineeprofile_preceptorship_country', to='zone.countries')),
            ],
            options={
                'db_table': 'TraineePreceptorshipProfile',
            },
        ),
    ]
