# Generated by Django 3.1.7 on 2021-09-10 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proctorship", "0001_initial"),
        ("preceptorship", "0001_initial"),
        ("feedback", "0002_auto_20210910_1209"),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="traineepreceptorshipprofile",
            name="current_preferential",
            field=models.ForeignKey(
                blank=True,
                db_column="CurrentPreferential",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preceptorship_current_preferential_constantdata",
                to="proctorship.constantdata",
            ),
        ),
        migrations.AddField(
            model_name="traineepreceptorshipprofile",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                db_column="HospitalTraineePreceptorshipProfileID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="traineeprofile_preceptorship_hospital",
                to="api.hospital",
            ),
        ),
        migrations.AddField(
            model_name="traineepreceptorshipprofile",
            name="preceptorship",
            field=models.ForeignKey(
                blank=True,
                db_column="TraineePreceptorship",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainee_preceptorship",
                to="preceptorship.preceptorship",
            ),
        ),
        migrations.AddField(
            model_name="traineepreceptorshipprofile",
            name="title",
            field=models.ForeignKey(
                blank=True,
                db_column="Title",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preceptorship_title_constantdata",
                to="proctorship.constantdata",
            ),
        ),
        migrations.AddField(
            model_name="preceptorshiptraineeuploads",
            name="preceptorship_trainee",
            field=models.ForeignKey(
                blank=True,
                db_column="TraineePreceptorship",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_preceptorship_trainee",
                to="preceptorship.traineepreceptorshipprofile",
            ),
        ),
        migrations.AddField(
            model_name="preceptorshiptraineeuploads",
            name="rate_corcym_support",
            field=models.ForeignKey(
                db_column="RateCorcymSupport",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rate_corcym_support_rating",
                to="feedback.rating",
            ),
        ),
        migrations.AddField(
            model_name="preceptorshiptraineeuploads",
            name="rate_experince_in_operating_room",
            field=models.ForeignKey(
                db_column="RateOfExperinceInOperatingRoom",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rate_experince_in_operating_room_rating",
                to="feedback.rating",
            ),
        ),
        migrations.AddField(
            model_name="preceptorshiptraineeuploads",
            name="rate_hospital_facility",
            field=models.ForeignKey(
                db_column="RateOfFacility",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rate_hospital_facility_rating",
                to="feedback.rating",
            ),
        ),
        migrations.AddField(
            model_name="preceptorshiptraineeuploads",
            name="rate_level_of_training",
            field=models.ForeignKey(
                db_column="RateLevlOfTrainig",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rate_level_of_training_rating",
                to="feedback.rating",
            ),
        ),
        migrations.AddField(
            model_name="preceptorshiptraineeuploads",
            name="rate_of_demostration",
            field=models.ForeignKey(
                db_column="RteOfostration",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rate_of_demostration_rating",
                to="feedback.rating",
            ),
        ),
        migrations.AddField(
            model_name="preceptorshiptraineeuploads",
            name="rate_of_experince_overall",
            field=models.ForeignKey(
                db_column="OverallExperince",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="overall_experince_rating",
                to="feedback.rating",
            ),
        ),
        migrations.AddField(
            model_name="preceptorshipstatus",
            name="preceptorship_activity",
            field=models.ForeignKey(
                blank=True,
                db_column="PreceptorshipStatusId",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preceptorshipStatus_status",
                to="preceptorship.preceptorship",
            ),
        ),
    ]
