# Generated by Django 3.1.7 on 2021-09-10 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("preceptorship", "0002_auto_20210910_1209"),
        ("status", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="preceptorshipstatus",
            name="status",
            field=models.ForeignKey(
                db_column="Status",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preceptorship_status_data",
                to="status.statusconstantdata",
            ),
        ),
    ]
