# Generated by Django 3.1.7 on 2021-09-10 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proctors', '0001_initial'),
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proctorship', '0001_initial'),
        ('preceptorship', '0003_preceptorshipstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='preceptorshipstatus',
            name='user',
            field=models.ForeignKey(db_column='UserId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preceptorship_status_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preceptorshipproposal',
            name='status',
            field=models.ForeignKey(blank=True, db_column='StatusId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alter_preceptorship_porposal', to='preceptorship.preceptorshipstatus'),
        ),
        migrations.AddField(
            model_name='preceptorshipproctors',
            name='preceptorship_proposal',
            field=models.ForeignKey(db_column='PreceptorshipPorposalID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preceptorship_porposal', to='preceptorship.preceptorshipproposal'),
        ),
        migrations.AddField(
            model_name='preceptorshipproctors',
            name='proctors',
            field=models.ForeignKey(db_column='ProctorsID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Preceptorship_proctor_data', to='proctors.proctors'),
        ),
        migrations.AddField(
            model_name='preceptorship',
            name='hospital',
            field=models.ForeignKey(blank=True, db_column='HospitalPreceptorshipID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preceptorship_hospital', to='api.hospital'),
        ),
        migrations.AddField(
            model_name='preceptorship',
            name='not_implant_regularly',
            field=models.ForeignKey(blank=True, db_column='NotImplantRegularly', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preceptorship_not_implant_regularly_constantdata', to='proctorship.constantdata'),
        ),
        migrations.AddField(
            model_name='preceptorship',
            name='product',
            field=models.ForeignKey(db_column='ProductID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perceptorship_product', to='api.products'),
        ),
        migrations.AddField(
            model_name='preceptorship',
            name='secondary_product',
            field=models.ForeignKey(db_column='SecondaryProductID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perceptorship_secondary_product', to='api.products'),
        ),
        migrations.AddField(
            model_name='preceptorship',
            name='specific_training',
            field=models.ForeignKey(blank=True, db_column='SpecificTraining', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preceptorship_specific_training_constantdata', to='proctorship.constantdata'),
        ),
        migrations.AddField(
            model_name='preceptorship',
            name='training_type',
            field=models.ForeignKey(blank=True, db_column='TrainingType', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preceptorship_training_Type_constantdata', to='proctorship.constantdata'),
        ),
        migrations.AddField(
            model_name='preceptorship',
            name='type_advance_training',
            field=models.ForeignKey(blank=True, db_column='TypesofAdvancedTraining', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preceptorship_type_advance_training_constantdata', to='proctorship.constantdata'),
        ),
        migrations.AddField(
            model_name='preceptorship',
            name='types_of_first_training',
            field=models.ForeignKey(blank=True, db_column='TypesOfFirstTraining', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preceptorship_types_of_first_training_constantdata', to='proctorship.constantdata'),
        ),
        migrations.AddField(
            model_name='preceptorship',
            name='user',
            field=models.ForeignKey(db_column='PreceptorshipUserID', on_delete=django.db.models.deletion.CASCADE, related_name='preceptorship_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceperceptorship',
            name='preceptorship',
            field=models.ForeignKey(db_column='PreceptorshipID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preceptorship_invoice', to='preceptorship.preceptorship'),
        ),
        migrations.AddField(
            model_name='attendanceformperceptorship',
            name='preceptorship',
            field=models.ForeignKey(db_column='PreceptorshipID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preceptorship_attendance_form', to='preceptorship.preceptorship'),
        ),
    ]
