# Generated by Django 3.1.7 on 2021-09-17 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0002_auto_20210915_1749'),
        ('preceptorship', '0006_preceptorship_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preceptorship',
            name='zone',
            field=models.ForeignKey(db_column='PerceptorshipZoneID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prceptors_zone_countries', to='zone.zone'),
        ),
    ]
