# Generated by Django 3.1.7 on 2021-09-10 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Countries",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.SlugField(db_column="Code", default="")),
            ],
            options={
                "db_table": "Countries",
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="ZoneName", default=None, max_length=255, unique=True
                    ),
                ),
                ("code", models.SlugField(db_column="Code", default="")),
            ],
            options={
                "db_table": "Zone",
            },
        ),
        migrations.CreateModel(
            name="ZoneCountries",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                ("status", models.BooleanField(db_column="ZoneStatus", default=True)),
                (
                    "countries",
                    models.ForeignKey(
                        blank=True,
                        db_column="CountriesID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_countires",
                        to="zone.countries",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        db_column="ZoneID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_zone_countires",
                        to="zone.zone",
                    ),
                ),
            ],
            options={
                "db_table": "ZoneCountries",
            },
        ),
    ]
