# Generated by Django 3.1.7 on 2021-09-10 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proctorship", "0001_initial"),
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="proctorship",
            field=models.ForeignKey(
                db_column="ProctorShipID",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proctorship_invoice",
                to="proctorship.proctorship",
            ),
        ),
        migrations.AddField(
            model_name="attendanceform",
            name="proctorship",
            field=models.ForeignKey(
                db_column="ProctorShipID",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proctorship_attendance_form",
                to="proctorship.proctorship",
            ),
        ),
    ]
