# Generated by Django 3.1.7 on 2021-09-10 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newmics', '0001_initial'),
        ('proctors', '0001_initial'),
        ('api', '0001_initial'),
        ('status', '0001_initial'),
        ('proctorship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmics',
            name='user',
            field=models.ForeignKey(db_column='MicsUserID', on_delete=django.db.models.deletion.CASCADE, related_name='mics_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='micstraineeprofile',
            name='country',
            field=models.ForeignKey(blank=True, db_column='CountriesTraineeProfileID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_traineeprofile_country', to='zone.countries'),
        ),
        migrations.AddField(
            model_name='micstraineeprofile',
            name='current_preferential',
            field=models.ForeignKey(blank=True, db_column='CurrentPreferential', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_current_preferential_constantdata', to='proctorship.constantdata'),
        ),
        migrations.AddField(
            model_name='micstraineeprofile',
            name='hospital',
            field=models.ForeignKey(blank=True, db_column='HospitalTraineeProfileID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_traineeprofile_hospital', to='api.hospital'),
        ),
        migrations.AddField(
            model_name='micstraineeprofile',
            name='mics',
            field=models.ForeignKey(blank=True, db_column='MicsCourseId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_traineeprofile', to='newmics.newmics'),
        ),
        migrations.AddField(
            model_name='micstraineeprofile',
            name='title',
            field=models.ForeignKey(blank=True, db_column='Title', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_title_constantdata', to='proctorship.constantdata'),
        ),
        migrations.AddField(
            model_name='micsproctorshipstatus',
            name='proctorship_activity',
            field=models.ForeignKey(blank=True, db_column='ProctorShipId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_proctorship_status', to='newmics.micsproctorship'),
        ),
        migrations.AddField(
            model_name='micsproctorshipstatus',
            name='status',
            field=models.ForeignKey(db_column='Status', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_proctorship_status_data', to='status.statusconstantdata'),
        ),
        migrations.AddField(
            model_name='micsproctorshipstatus',
            name='user',
            field=models.ForeignKey(db_column='UserId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_proctorship_status_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='micsproctorshipproposal',
            name='status',
            field=models.ForeignKey(blank=True, db_column='StatusId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_proctorship_porposal', to='newmics.micsproctorshipstatus'),
        ),
        migrations.AddField(
            model_name='micsproctorshipproctors',
            name='porposal',
            field=models.ForeignKey(db_column='PorposalID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_proctor_porposal', to='newmics.micsproctorshipproposal'),
        ),
        migrations.AddField(
            model_name='micsproctorshipproctors',
            name='proctors',
            field=models.ForeignKey(db_column='ProctorsID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_porposal_proctor_id', to='proctors.proctors'),
        ),
        migrations.AddField(
            model_name='micsproctorship',
            name='country',
            field=models.ForeignKey(db_column='CountriesProctorshipID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_proctorship_country', to='zone.countries'),
        ),
        migrations.AddField(
            model_name='micsproctorship',
            name='hospital',
            field=models.ForeignKey(db_column='HospitalProctorshipID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_proctorship_hospital', to='api.hospital'),
        ),
        migrations.AddField(
            model_name='micsproctorship',
            name='mics',
            field=models.ForeignKey(blank=True, db_column='MicsCourseId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_peroctorship', to='newmics.newmics'),
        ),
        migrations.AddField(
            model_name='micsproctorship',
            name='user',
            field=models.ForeignKey(db_column='ProctorshipUserID', on_delete=django.db.models.deletion.CASCADE, related_name='mics_proctorship_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='micspreceptorshipstatus',
            name='mics_preceptorship_activity',
            field=models.ForeignKey(blank=True, db_column='MicsPreceptorshipStatusId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_preceptorshipStatus_status', to='newmics.micspreceptorship'),
        ),
        migrations.AddField(
            model_name='micspreceptorshipstatus',
            name='status',
            field=models.ForeignKey(db_column='Status', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_preceptorship_status_data', to='status.statusconstantdata'),
        ),
        migrations.AddField(
            model_name='micspreceptorshipstatus',
            name='user',
            field=models.ForeignKey(db_column='UserId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_preceptorship_status_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='micspreceptorshipproposal',
            name='status',
            field=models.ForeignKey(blank=True, db_column='StatusId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alter_mics_preceptorship_porposal', to='newmics.micspreceptorshipstatus'),
        ),
        migrations.AddField(
            model_name='micspreceptorshipproctors',
            name='mics_preceptorship_proposal',
            field=models.ForeignKey(db_column='PreceptorshipPorposalID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_preceptorship_porposal', to='newmics.micspreceptorshipproposal'),
        ),
        migrations.AddField(
            model_name='micspreceptorshipproctors',
            name='proctors',
            field=models.ForeignKey(db_column='ProctorsID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_preceptorship_proctor_data', to='proctors.proctors'),
        ),
        migrations.AddField(
            model_name='micspreceptorship',
            name='hospital',
            field=models.ForeignKey(blank=True, db_column='HospitalMicsPreceptorshipID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_preceptorship_hospital', to='api.hospital'),
        ),
        migrations.AddField(
            model_name='micspreceptorship',
            name='mics',
            field=models.ForeignKey(blank=True, db_column='MicsCourseId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_perceptotship', to='newmics.newmics'),
        ),
        migrations.AddField(
            model_name='micspreceptorship',
            name='product',
            field=models.ForeignKey(db_column='ProductID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_perceptorship_product', to='api.products'),
        ),
        migrations.AddField(
            model_name='micspreceptorship',
            name='user',
            field=models.ForeignKey(db_column='MicsPreceptorshipUserID', on_delete=django.db.models.deletion.CASCADE, related_name='mics_preceptorship_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
