# Generated by Django 3.1.7 on 2021-09-19 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_auto_20210910_1209"),
        ("newmics", "0003_micsproctorship_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="MicsTraineeFeedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                (
                    "implanted_perceval",
                    models.IntegerField(
                        db_column="NumberOfPercevalImplanted", default=None, null=True
                    ),
                ),
                (
                    "number_patient",
                    models.IntegerField(
                        db_column="NumberOfPatient", default=None, null=True
                    ),
                ),
                (
                    "need_further_training",
                    models.BooleanField(
                        db_column="DoYouFeelNeedFurtherTraining", default=False
                    ),
                ),
                (
                    "plan_for_next",
                    models.CharField(
                        blank=True,
                        db_column="PlanForNext",
                        default="",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "any_sugestion",
                    models.CharField(
                        blank=True,
                        db_column="AnySuggestionForCorcym",
                        default="",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "report",
                    models.FileField(
                        blank=True,
                        db_column="TraineeReport",
                        null=True,
                        upload_to="uploads/",
                    ),
                ),
                (
                    "is_memo_family",
                    models.BooleanField(db_column="IsMemoFmaily", default=False),
                ),
                (
                    "is_perceval",
                    models.BooleanField(db_column="IsPerceval", default=False),
                ),
                (
                    "is_solo_smart",
                    models.BooleanField(db_column="IsSoloSmart", default=False),
                ),
                (
                    "perceval_driver",
                    models.CharField(
                        blank=True,
                        db_column="KeyDriverForPerceval",
                        default="",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "mics_perceptership",
                    models.ForeignKey(
                        db_column="MicsPerceptershipID",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mics_trainee_feedback_mics_perceptership",
                        to="newmics.micspreceptorship",
                    ),
                ),
                (
                    "mics_proctorship",
                    models.ForeignKey(
                        db_column="MicsProctorshipID",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mics_trainee_feedback_mics_proctorship",
                        to="newmics.micsproctorship",
                    ),
                ),
                (
                    "rate_of_experince",
                    models.ForeignKey(
                        db_column="RateOfExperinceOfProctorship",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mics_trainee_feedback_experince",
                        to="feedback.rating",
                    ),
                ),
                (
                    "rate_of_training",
                    models.ForeignKey(
                        db_column="RateOfTrainingOfProctorship",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mics_trainee_feedback_training_rating",
                        to="feedback.rating",
                    ),
                ),
            ],
            options={
                "db_table": "MicsTraineeFeedback",
            },
        ),
        migrations.CreateModel(
            name="MicsPercevalFeedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                (
                    "num_of_patients",
                    models.IntegerField(
                        db_column="NumberOfPatients", default=None, null=True
                    ),
                ),
                (
                    "is_advance",
                    models.BooleanField(
                        db_column="IsPateintDataAdvance", default=False
                    ),
                ),
                (
                    "implanted_patient",
                    models.IntegerField(
                        db_column="NumberOfPatientOperated", default=None, null=True
                    ),
                ),
                (
                    "implanted_perceval",
                    models.IntegerField(
                        db_column="NumberOfPercevalImplanted", default=None, null=True
                    ),
                ),
                (
                    "is_trainee_implant",
                    models.BooleanField(
                        db_column="IsTraineeImplantWithOutProctor", default=False
                    ),
                ),
                (
                    "any_leason",
                    models.TextField(db_column="AnyLeasonThatYouWantToShare"),
                ),
                (
                    "report",
                    models.FileField(
                        blank=True,
                        db_column="ProctorReport",
                        null=True,
                        upload_to="uploads/",
                    ),
                ),
                (
                    "mics_perceptership",
                    models.ForeignKey(
                        db_column="MicsPerceptershipID",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mics_perceval_feedback_mics_perceptership",
                        to="newmics.micspreceptorship",
                    ),
                ),
                (
                    "mics_proctorship",
                    models.ForeignKey(
                        db_column="MicsProctorshipID",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mics_perceval_feedback_mics_proctorship",
                        to="newmics.micsproctorship",
                    ),
                ),
                (
                    "rate_of_experince",
                    models.ForeignKey(
                        db_column="RateOfExperinceOfProctorship",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mics_perceval_feedback_rating",
                        to="feedback.rating",
                    ),
                ),
                (
                    "reason_low_num_patients",
                    models.ForeignKey(
                        db_column="IfNumberOfPatientIsLowReason",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mics_perceval_feedback_reason",
                        to="feedback.reason",
                    ),
                ),
            ],
            options={
                "db_table": "MicsPercevalFeedback",
            },
        ),
        migrations.CreateModel(
            name="MicsInvoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        db_column="InvoiceNumber",
                        default=None,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "fee_covered",
                    models.CharField(
                        db_column="FEECoveredbyMedicalAffair",
                        default="",
                        max_length=255,
                    ),
                ),
                (
                    "other_cost",
                    models.CharField(
                        db_column="OtherCostsCoveredByMedicalAffair",
                        default="",
                        max_length=255,
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(db_column="DateOfInvoice", default=None),
                ),
                ("note", models.TextField(db_column="Note", default="")),
                (
                    "invoice_sent",
                    models.BooleanField(
                        db_column="InvoicesSentToTheAdministration", default=False
                    ),
                ),
                (
                    "mics_perceptership",
                    models.ForeignKey(
                        db_column="MicsPerceptershipID",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mics_invoice_mics_perceptership",
                        to="newmics.micspreceptorship",
                    ),
                ),
                (
                    "mics_proctorship",
                    models.ForeignKey(
                        db_column="MicsProctorshipID",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mics_invoice_mics_proctorship",
                        to="newmics.micsproctorship",
                    ),
                ),
            ],
            options={
                "db_table": "MicsInvoice",
            },
        ),
        migrations.CreateModel(
            name="MicsAttendanceForm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                (
                    "attendance_form",
                    models.FileField(
                        blank=True,
                        db_column="AttendanceForm",
                        default=None,
                        null=True,
                        upload_to="uploads/",
                    ),
                ),
                (
                    "mics_perceptership",
                    models.ForeignKey(
                        db_column="MicsPerceptershipID",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mics_attendance_form_mics_perceptership",
                        to="newmics.micspreceptorship",
                    ),
                ),
                (
                    "mics_proctorship",
                    models.ForeignKey(
                        db_column="MicsProctorshipID",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mics_attendance_form_mics_proctorship",
                        to="newmics.micsproctorship",
                    ),
                ),
            ],
            options={
                "db_table": "MicsAttendanceForm",
            },
        ),
    ]
