# Generated by Django 3.1.7 on 2021-09-19 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newmics', '0004_micsattendanceform_micsinvoice_micspercevalfeedback_micstraineefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='micstraineefeedback',
            name='trainee',
            field=models.ForeignKey(db_column='MicsTraineeProfileID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mics_trainee_feedback_mics_trainee_profile', to='newmics.micstraineeprofile'),
        ),
    ]
