# Generated by Django 3.1.7 on 2021-09-20 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newmics", "0005_micstraineefeedback_trainee"),
    ]

    operations = [
        migrations.CreateModel(
            name="MicsProctorshipCertificateForm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                (
                    "certificate",
                    models.FileField(
                        blank=True,
                        db_column="Certificate",
                        default=None,
                        null=True,
                        upload_to="uploads/",
                    ),
                ),
                (
                    "mics_perceptership",
                    models.ForeignKey(
                        db_column="MicsPerceptershipID",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mics_certificate_form_mics_perceptership",
                        to="newmics.micspreceptorship",
                    ),
                ),
                (
                    "mics_proctorship",
                    models.ForeignKey(
                        db_column="MicsProctorshipID",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mics_certificate_form_mics_proctorship",
                        to="newmics.micsproctorship",
                    ),
                ),
            ],
            options={
                "db_table": "MicsProctorshipCertificateForm",
            },
        ),
    ]
