# Generated by Django 3.1.7 on 2021-09-10 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zone", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Approach",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="ApproachName", default="", max_length=255
                    ),
                ),
                ("code", models.SlugField(db_column="Code", default="")),
            ],
            options={
                "db_table": "Approach",
            },
        ),
        migrations.CreateModel(
            name="AreaOfExperties",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="AreaOfExpertiesName", default="", max_length=255
                    ),
                ),
                ("code", models.SlugField(db_column="Code", default="")),
            ],
            options={
                "db_table": "AreaOfExperties",
            },
        ),
        migrations.CreateModel(
            name="Audience",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                ("audience", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "Audience",
            },
        ),
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="AreaOfExpertiesName", default="", max_length=255
                    ),
                ),
                (
                    "code",
                    models.SlugField(db_column="Code", default="", max_length=255),
                ),
            ],
            options={
                "db_table": "EventType",
            },
        ),
        migrations.CreateModel(
            name="Hcp_role",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                ("name_of_role", models.CharField(max_length=255)),
                ("code", models.CharField(default="", max_length=255)),
            ],
            options={
                "db_table": "Hcp_role",
            },
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                (
                    "hospital_name",
                    models.CharField(
                        blank=True, db_column="HospitalName", max_length=255, null=True
                    ),
                ),
                ("number_of_trainee", models.IntegerField(default=0)),
                (
                    "location",
                    models.CharField(db_column="Location", default="", max_length=255),
                ),
                (
                    "is_it_preceptorship",
                    models.BooleanField(db_column="IsItPreceptorship", default=False),
                ),
                (
                    "qualified_for_news_mics_program",
                    models.BooleanField(
                        db_column="QualifiedForNewsMicsProgram", default=False
                    ),
                ),
                (
                    "cognos_id",
                    models.CharField(
                        blank=True,
                        db_column="CognosID",
                        default="",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "code",
                    models.SlugField(db_column="Code", default="", max_length=255),
                ),
                ("deleted", models.BooleanField(db_column="Deleted", default=False)),
            ],
            options={
                "db_table": "Hospital",
            },
        ),
        migrations.CreateModel(
            name="Languages",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                ("code", models.SlugField(db_column="Code", default="")),
            ],
            options={
                "db_table": "Languages",
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("image", models.ImageField(default="", upload_to="")),
                ("code", models.SlugField(db_column="Code", default="")),
            ],
            options={
                "db_table": "Products",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "Region",
            },
        ),
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                ("solution", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "Solution",
            },
        ),
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="AreaOfExpertiesName", default="", max_length=255
                    ),
                ),
                ("code", models.SlugField(db_column="Code", default="")),
            ],
            options={
                "db_table": "Speciality",
            },
        ),
        migrations.CreateModel(
            name="HospitalCountires",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_column="CreatedBy", default=0, null=True
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedOn"),
                ),
                (
                    "modified_by",
                    models.BigIntegerField(
                        blank=True, db_column="ModifiedBy", default=0, null=True
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, db_column="ModifiedOn"),
                ),
                (
                    "deleted_by",
                    models.BigIntegerField(
                        blank=True, db_column="DeletedBy", default=0, null=True
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(auto_now=True, db_column="DeletedOn"),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        db_column="Status",
                        default=0,
                        help_text="Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        db_column="HospitalCountry",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_country",
                        to="zone.countries",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        db_column="HospitalId",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_id",
                        to="api.hospital",
                    ),
                ),
            ],
            options={
                "db_table": "HospitalCountires",
            },
        ),
        migrations.AddField(
            model_name="hospital",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                db_column="HospitalProducts",
                related_name="hospitals_products",
                to="api.Products",
            ),
        ),
    ]
