# Generated by Django 3.1.7 on 2021-09-10 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proctors", "0002_proctors_user"),
        ("status", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="user",
            field=models.ForeignKey(
                db_column="UserId",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="status",
            field=models.ForeignKey(
                blank=True,
                db_column="StatusId",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alter_proctorship_porposal",
                to="status.status",
            ),
        ),
        migrations.AddField(
            model_name="proctorshipproctors",
            name="porposal",
            field=models.ForeignKey(
                db_column="PorposalID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proctor_porposal",
                to="status.proposal",
            ),
        ),
        migrations.AddField(
            model_name="proctorshipproctors",
            name="proctors",
            field=models.ForeignKey(
                db_column="ProctorsID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="porposal_proctor_id",
                to="proctors.proctors",
            ),
        ),
    ]
