# Generated by Django 3.1.7 on 2021-09-10 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proctorship', '0001_initial'),
        ('zone', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='DeletedBy', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now=True, db_column='DeletedOn')),
                ('name', models.CharField(db_column='Name', default='', max_length=255)),
                ('surname', models.CharField(db_column='SurName', default='', max_length=255)),
                ('corcym_accompanying_rep', models.CharField(blank=True, db_column='CorcymAccompanyingRep', default='', max_length=255, null=True)),
                ('mvr_case_per_year', models.IntegerField(db_column='MVRCasePerYear')),
                ('mvr_case_per_year_by_trainee', models.IntegerField(db_column='MVRCasePerYearByTrainee')),
                ('note', models.TextField(db_column='Note')),
                ('status', models.BooleanField(db_column='Status', default=False)),
                ('revoke', models.BooleanField(db_column='Revoke', default=False)),
                ('interest_invasive', models.BooleanField(db_column='InterestInvasive', default=False)),
                ('country', models.ForeignKey(blank=True, db_column='CountriesTraineeProfileID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traineeprofile_country', to='zone.countries')),
                ('current_preferential', models.ForeignKey(blank=True, db_column='CurrentPreferential', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_preferential_constantdata', to='proctorship.constantdata')),
                ('hospital', models.ForeignKey(blank=True, db_column='HospitalTraineeProfileID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traineeprofile_hospital', to='api.hospital')),
                ('proctorship', models.ForeignKey(blank=True, db_column='TraineeProctorship', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainee_proctorship', to='proctorship.proctorship')),
                ('title', models.ForeignKey(blank=True, db_column='Title', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_constantdata', to='proctorship.constantdata')),
            ],
            options={
                'db_table': 'TraineeProfile',
            },
        ),
    ]
