# Generated by Django 3.1.7 on 2021-09-10 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zone', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstantData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='DeletedBy', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now=True, db_column='DeletedOn')),
                ('status', models.BigIntegerField(db_column='Status', default=0, help_text='Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose')),
                ('name', models.CharField(db_column='Name', default='', max_length=255)),
                ('code', models.SlugField(db_column='Code', default='')),
                ('type', models.CharField(db_column='Type', default='', max_length=255)),
                ('field', models.CharField(db_column='Field', default='', max_length=255)),
            ],
            options={
                'db_table': 'ConstantData',
            },
        ),
        migrations.CreateModel(
            name='Proctorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='DeletedBy', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now=True, db_column='DeletedOn')),
                ('status', models.BigIntegerField(db_column='Status', default=0, help_text='Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose')),
                ('note', models.TextField(db_column='Note')),
                ('memo_surgeon_implant', models.IntegerField(blank=True, db_column='MemoSurgeonImplant', default=None)),
                ('rechord_surgeon_implant', models.IntegerField(blank=True, db_column='ReChordSurgeonImplant', default=None)),
                ('other_num_of_implants', models.IntegerField(blank=True, db_column='NumberOfPercevel', null=True)),
                ('ETQ_number', models.IntegerField(blank=True, db_column='ETQNumber', default=None, null=True)),
                ('issue', models.CharField(blank=True, db_column='SpecificIssue', default='', max_length=100, null=True)),
                ('hotel', models.CharField(db_column='HotelName', default='', max_length=255)),
                ('number_of_cases', models.IntegerField(blank=True, db_column='NumberOfCases', default=None, null=True)),
                ('transplant_time', models.CharField(blank=True, db_column='TransplantTime', default='', max_length=255, null=True)),
                ('field_check', models.CharField(db_column='FieldForDataCheck', default='', max_length=255)),
                ('is_global', models.BooleanField(db_column='IsGlobal', default=False)),
                ('note_related_to_proctor', models.TextField(db_column='NoteRelatedToProctors', default=None)),
                ('country', models.ForeignKey(db_column='CountriesProctorshipID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctorship_country', to='zone.countries')),
                ('hospital', models.ForeignKey(db_column='HospitalProctorshipID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctorship_hospital', to='api.hospital')),
                ('new_center', models.ForeignKey(blank=True, db_column='NewCenter', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_center_constantdata', to='proctorship.constantdata')),
                ('not_implant_regularly', models.ForeignKey(blank=True, db_column='NotImplantRegularly', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='not_implant_regularly_constantdata', to='proctorship.constantdata')),
                ('other_advanced_training', models.ForeignKey(blank=True, db_column='OtherAdvancedTraining', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='proctorship.constantdata')),
                ('product', models.ForeignKey(db_column='ProductID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctorship_product', to='api.products')),
                ('secondary_product', models.ForeignKey(db_column='SecondaryProductID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctorship_secondary_product', to='api.products')),
                ('specific_training', models.ForeignKey(blank=True, db_column='SpecificTraining', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_training_constantdata', to='proctorship.constantdata')),
                ('training_type', models.ForeignKey(blank=True, db_column='TrainingType', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_Type_constantdata', to='proctorship.constantdata')),
                ('type_advance_training', models.ForeignKey(blank=True, db_column='TypesofAdvancedTraining', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_advance_training_constantdata', to='proctorship.constantdata')),
                ('types_of_first_training', models.ForeignKey(blank=True, db_column='TypesOfFirstTraining', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types_of_first_training_constantdata', to='proctorship.constantdata')),
            ],
            options={
                'db_table': 'Proctorship',
            },
        ),
    ]
