# Generated by Django 3.1.7 on 2021-09-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proctorship", "0002_auto_20210910_1209"),
    ]

    operations = [
        migrations.AddField(
            model_name="proctorship",
            name="first_proctorship_num",
            field=models.IntegerField(db_column="FirstPrcotorshipId", default=None),
        ),
    ]
