# Generated by Django 3.1.7 on 2021-09-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proctorship", "0003_proctorship_first_proctorship_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proctorship",
            name="first_proctorship_num",
            field=models.IntegerField(
                blank=True, db_column="FirstPrcotorshipId", default=None, null=True
            ),
        ),
    ]
