# Generated by Django 3.1.7 on 2021-09-10 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoProctorFeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='DeletedBy', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now=True, db_column='DeletedOn')),
                ('status', models.BigIntegerField(db_column='Status', default=0, help_text='Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose')),
                ('implanted_memo', models.IntegerField(db_column='NumberOfMemoImplanted', default=None, null=True)),
                ('is_trainee_implant', models.BooleanField(db_column='IsTraineeImplantWithOutProctor', default=False)),
                ('any_leason', models.TextField(db_column='AnyLeasonThatYouWantToShare')),
                ('report', models.FileField(blank=True, db_column='ProctorReport', null=True, upload_to='uploads/')),
            ],
            options={
                'db_table': 'MemoProctorFeedBack',
            },
        ),
        migrations.CreateModel(
            name='PercevelDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='DeletedBy', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now=True, db_column='DeletedOn')),
                ('status', models.BigIntegerField(db_column='Status', default=0, help_text='Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose')),
                ('code', models.SlugField(db_column='Code', default='', max_length=255)),
                ('name', models.CharField(db_column='Name', default='', max_length=255)),
            ],
            options={
                'db_table': 'PercevelDriver',
            },
        ),
        migrations.CreateModel(
            name='ProctorshipProctorFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='DeletedBy', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now=True, db_column='DeletedOn')),
                ('status', models.BigIntegerField(db_column='Status', default=0, help_text='Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose')),
                ('num_of_patients', models.IntegerField(db_column='NumberOfPatients', default=None, null=True)),
                ('is_advance', models.BooleanField(db_column='IsPateintDataAdvance', default=False)),
                ('implanted_patient', models.IntegerField(db_column='NumberOfPatientOperated', default=None, null=True)),
                ('implanted_perceval', models.IntegerField(db_column='NumberOfPercevalImplanted', default=None, null=True)),
                ('is_trainee_implant', models.BooleanField(db_column='IsTraineeImplantWithOutProctor', default=False)),
                ('any_leason', models.TextField(db_column='AnyLeasonThatYouWantToShare')),
                ('report', models.FileField(blank=True, db_column='ProctorReport', null=True, upload_to='uploads/')),
            ],
            options={
                'db_table': 'ProctorshipProctorFeedback',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='DeletedBy', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now=True, db_column='DeletedOn')),
                ('status', models.BigIntegerField(db_column='Status', default=0, help_text='Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose')),
                ('code', models.SlugField(db_column='Code', default='', max_length=255)),
                ('name', models.CharField(db_column='Name', default='', max_length=255)),
            ],
            options={
                'db_table': 'Rating',
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='DeletedBy', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now=True, db_column='DeletedOn')),
                ('status', models.BigIntegerField(db_column='Status', default=0, help_text='Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose')),
                ('code', models.SlugField(db_column='Code', default='', max_length=255)),
                ('name', models.CharField(db_column='Name', default='', max_length=255)),
            ],
            options={
                'db_table': 'Reason',
            },
        ),
        migrations.CreateModel(
            name='SoloSmartProctorFeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='DeletedBy', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now=True, db_column='DeletedOn')),
                ('status', models.BigIntegerField(db_column='Status', default=0, help_text='Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose')),
                ('implanted_solo_smart', models.IntegerField(db_column='NumberOfMemoImplanted', default=None, null=True)),
                ('is_trainee_implant', models.BooleanField(db_column='IsTraineeImplantWithOutProctor', default=False)),
                ('any_leason', models.TextField(db_column='AnyLeasonThatYouWantToShare')),
                ('report', models.FileField(blank=True, db_column='ProctorReport', null=True, upload_to='uploads/')),
            ],
            options={
                'db_table': 'SoloSmartProctorFeedBack',
            },
        ),
        migrations.CreateModel(
            name='TraineeFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='DeletedBy', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now=True, db_column='DeletedOn')),
                ('status', models.BigIntegerField(db_column='Status', default=0, help_text='Be default 0 which has no meaning this field is used for making the status like pending approved and for some other purpose')),
                ('implanted_perceval', models.IntegerField(db_column='NumberOfPercevalImplanted', default=None, null=True)),
                ('number_patient', models.IntegerField(db_column='NumberOfPatient', default=None, null=True)),
                ('need_further_training', models.BooleanField(db_column='DoYouFeelNeedFurtherTraining', default=False)),
                ('plan_for_next', models.CharField(blank=True, db_column='PlanForNext', default='', max_length=255, null=True)),
                ('any_sugestion', models.CharField(blank=True, db_column='AnySuggestionForCorcym', default='', max_length=255, null=True)),
                ('report', models.FileField(blank=True, db_column='TraineeReport', null=True, upload_to='uploads/')),
                ('is_memo_family', models.BooleanField(db_column='IsMemoFmaily', default=False)),
                ('is_perceval', models.BooleanField(db_column='IsPerceval', default=False)),
                ('is_solo_smart', models.BooleanField(db_column='IsSoloSmart', default=False)),
                ('perceval_driver', models.CharField(blank=True, db_column='KeyDriverForPerceval', default='', max_length=255, null=True)),
                ('rate_of_experince', models.ForeignKey(db_column='RateOfExperinceOfProctorship', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainee_feedback_experince', to='feedback.rating')),
                ('rate_of_training', models.ForeignKey(db_column='RateOfTrainingOfProctorship', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainee_feedback_training_rating', to='feedback.rating')),
            ],
            options={
                'db_table': 'TraineeFeedback',
            },
        ),
    ]
