# Generated by Django 3.1.7 on 2021-09-10 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proctorship", "0001_initial"),
        ("feedback", "0001_initial"),
        ("trainee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="traineefeedback",
            name="trainee",
            field=models.ForeignKey(
                db_column="TraineeFeedbackid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trianee_feedback_id",
                to="trainee.traineeprofile",
            ),
        ),
        migrations.AddField(
            model_name="solosmartproctorfeedback",
            name="proctorship",
            field=models.ForeignKey(
                db_column="ProctorshipId",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proctor_solo_feedback_proctorship",
                to="proctorship.proctorship",
            ),
        ),
        migrations.AddField(
            model_name="solosmartproctorfeedback",
            name="rate_of_experince",
            field=models.ForeignKey(
                db_column="RateOfExperinceOfMemoProctorship",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proctor_solo_feedback_rating",
                to="feedback.rating",
            ),
        ),
        migrations.AddField(
            model_name="proctorshipproctorfeedback",
            name="proctorship",
            field=models.ForeignKey(
                db_column="ProctorshipId",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proctor_feedback_proctorship",
                to="proctorship.proctorship",
            ),
        ),
        migrations.AddField(
            model_name="proctorshipproctorfeedback",
            name="rate_of_experince",
            field=models.ForeignKey(
                db_column="RateOfExperinceOfProctorship",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proctor_feedback_rating",
                to="feedback.rating",
            ),
        ),
        migrations.AddField(
            model_name="proctorshipproctorfeedback",
            name="reason_low_num_patients",
            field=models.ForeignKey(
                db_column="IfNumberOfPatientIsLowReason",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proctor_feedback_reason",
                to="feedback.reason",
            ),
        ),
        migrations.AddField(
            model_name="memoproctorfeedback",
            name="proctorship",
            field=models.ForeignKey(
                db_column="ProctorshipId",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proctor_memo_feedback_proctorship",
                to="proctorship.proctorship",
            ),
        ),
        migrations.AddField(
            model_name="memoproctorfeedback",
            name="rate_of_experince",
            field=models.ForeignKey(
                db_column="RateOfExperinceOfMemoProctorship",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proctor_memo_feedback_rating",
                to="feedback.rating",
            ),
        ),
    ]
