# Generated by Django 3.1.7 on 2021-09-10 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proctors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="proctors",
            name="user",
            field=models.ForeignKey(
                db_column="UserId",
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proctor_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
