# Generated by Django 3.1.7 on 2021-09-10 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speakingevent', '0001_initial'),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstatus',
            name='status',
            field=models.ForeignKey(db_column='EventStatus', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_status_data', to='status.statusconstantdata'),
        ),
    ]
