# Generated by Django 3.1.7 on 2021-09-10 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("speakingevent", "0002_eventstatus_status"),
        ("zone", "0001_initial"),
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventstatus",
            name="user",
            field=models.ForeignKey(
                db_column="UserId",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_status_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="event_country",
            field=models.ForeignKey(
                db_column="EventCountryId",
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_country",
                to="zone.countries",
            ),
        ),
        migrations.AddField(
            model_name="cognosid",
            name="cognos",
            field=models.ForeignKey(
                db_column="EventID",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cognos_id_speaker",
                to="api.hospital",
            ),
        ),
        migrations.AddField(
            model_name="cognosid",
            name="event",
            field=models.ForeignKey(
                db_column="EventCognosID",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_cognos_id",
                to="speakingevent.event",
            ),
        ),
        migrations.AddField(
            model_name="attendanceformspeakingevent",
            name="event",
            field=models.ForeignKey(
                db_column="EventID",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_attendance_form",
                to="speakingevent.event",
            ),
        ),
    ]
