# Generated by Django 3.1.7 on 2021-09-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakingevent', '0006_event_activity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meeting_docs',
            field=models.FileField(blank=True, db_column='MeetingDocs', null=True, upload_to='uploads/'),
        ),
    ]
